// Teaching content for each skill: a plain-English explanation, a "why does
// this matter?" hook, and one fully worked example with step-by-step reasoning.
// Kept short on purpose — the UI shows one idea at a time, never a wall of text.

export const TOPICS = {
  'place-value': {
    title: 'Place Value',
    concept: 'Every digit in a number has a "place" — ones, tens, hundreds, and so on. The place tells you how much that digit is really worth. The digit 7 means 7 ones, but in 700 it means 7 hundreds.',
    why: 'Place value is how we read prices, populations, and distances. Without it, 45 and 54 would look the same!',
    example: { problem: 'What is the value of 4 in 3,400?', steps: ['The 4 sits in the hundreds place.', 'Hundreds place is worth 100.', '4 × 100 = 400.'] },
    visual: '3 4 0 0\n│ │ │ └ ones\n│ │ └── tens\n│ └──── hundreds\n└────── thousands',
  },
  'compare-order': {
    title: 'Comparing & Ordering',
    concept: 'To compare numbers, first count the digits — more digits usually means a bigger number. If they match, compare digit by digit from the left.',
    why: 'You compare numbers every time you pick the better price, the higher score, or the faster time.',
    example: { problem: 'Which is bigger: 5,281 or 5,271?', steps: ['Same number of digits (4).', 'Thousands match (5), hundreds match (2).', 'Tens: 8 vs 7 → 5,281 is bigger.'] },
  },
  'rounding': {
    title: 'Rounding',
    concept: 'Rounding makes a number simpler while keeping it close. Look at the digit just to the right of your rounding place: 5 or more rounds up, 4 or less stays.',
    why: 'Rounding lets you estimate quickly — like knowing $19.75 is "about $20".',
    example: { problem: 'Round 348 to the nearest hundred.', steps: ['Hundreds digit is 3.', 'Digit to the right is 4 → round down.', 'Answer: 300.'] },
  },
  'add-sub': {
    title: 'Addition & Subtraction',
    concept: 'Line numbers up by place value and work right to left. Carry when a column passes 9; borrow when the top digit is too small.',
    why: 'Adding and subtracting is money math — totals, change, and keeping score.',
    example: { problem: '352 − 178', steps: ['Ones: 2 − 8 needs borrowing → 12 − 8 = 4.', 'Tens: 4 − 7 needs borrowing → 14 − 7 = 7.', 'Hundreds: 2 − 1 = 1. Answer: 174.'] },
  },
  'mult-div': {
    title: 'Multiplication & Division',
    concept: 'Multiplication is repeated addition (groups of equal size). Division splits a total into equal groups. They undo each other.',
    why: 'Multiplication scales recipes and prices; division shares things fairly.',
    example: { problem: '6 × 7', steps: ['6 groups of 7.', 'Think 6×7 = 42.', 'Check: 42 ÷ 7 = 6.'] },
  },
  'pemdas': {
    title: 'Order of Operations (PEMDAS)',
    concept: 'When an expression has several operations, do them in order: Parentheses, Exponents, Multiply/Divide (left to right), then Add/Subtract.',
    why: 'Everyone must agree on the order, or the same expression would give different answers.',
    example: { problem: '2 + 3 × 4', steps: ['Multiply first: 3 × 4 = 12.', 'Then add: 2 + 12 = 14.', 'Not 20 — multiplication comes before addition.'] },
    visual: 'P → E → MD → AS',
  },
  'fraction-intro': {
    title: 'What Is a Fraction?',
    concept: 'A fraction shows part of a whole. The bottom (denominator) is how many equal parts the whole is split into; the top (numerator) is how many you have.',
    why: 'Fractions are everywhere — half a pizza, a quarter of an hour, three-quarters full.',
    example: { problem: 'You eat 3 of 8 pizza slices. What fraction?', steps: ['8 equal slices → denominator 8.', 'You ate 3 → numerator 3.', 'Fraction: 3/8.'] },
    visual: '🍕 ▰▰▰▱▱▱▱▱  = 3/8',
  },
  'equivalent-fractions': {
    title: 'Equivalent Fractions',
    concept: 'Multiply (or divide) the top and bottom by the same number and the fraction keeps the same value. 1/2 = 2/4 = 3/6.',
    why: 'You need equal fractions to add, compare, and simplify fractions.',
    example: { problem: 'Make 2/3 into sixths.', steps: ['Bottom 3 → 6 means ×2.', 'Do the same on top: 2 × 2 = 4.', '2/3 = 4/6.'] },
  },
  'compare-fractions': {
    title: 'Comparing Fractions',
    concept: 'Give both fractions the same denominator, then just compare the numerators. Bigger top (with equal bottoms) means bigger fraction.',
    why: 'Which deal gives more — 2/3 of a bar or 3/5? Comparing fractions answers it.',
    example: { problem: 'Compare 2/3 and 3/5.', steps: ['Common denominator 15.', '2/3 = 10/15, 3/5 = 9/15.', '10 > 9, so 2/3 > 3/5.'] },
  },
  'add-sub-fractions': {
    title: 'Adding & Subtracting Fractions',
    concept: 'Same denominators: just add or subtract the tops. Different denominators: rewrite them with a common denominator first, then combine.',
    why: 'Combining fractions is how you total ingredients or measure lengths.',
    example: { problem: '1/4 + 2/4', steps: ['Denominators match (4).', 'Add tops: 1 + 2 = 3.', 'Answer: 3/4.'] },
  },
  'decimals-read': {
    title: 'Reading & Writing Decimals',
    concept: 'Decimals extend place value past the ones. The places after the point are tenths, hundredths, thousandths.',
    why: 'Money and measurements are written as decimals — $3.75, 1.5 meters.',
    example: { problem: 'Name the 5 in 2.35', steps: ['First place after point = tenths (3).', 'Second place = hundredths (5).', 'So 5 is in the hundredths place.'] },
  },
  'fraction-decimal': {
    title: 'Fractions ↔ Decimals',
    concept: 'A fraction is a division: top ÷ bottom gives its decimal. To reverse, put the decimal digits over 10, 100, or 1000 and reduce.',
    why: 'Switching forms lets you use whichever is easier for the problem.',
    example: { problem: 'Write 3/4 as a decimal.', steps: ['3/4 means 3 ÷ 4.', '3 ÷ 4 = 0.75.', 'So 3/4 = 0.75.'] },
  },
  'add-sub-decimals': {
    title: 'Adding & Subtracting Decimals',
    concept: 'Line up the decimal points (not just the digits!). Add zeros so both numbers are the same length, then add or subtract normally.',
    why: 'Every receipt total is decimal addition.',
    example: { problem: '1.5 + 2.25', steps: ['Line up points: 1.50 + 2.25.', 'Add columns: 1.50 + 2.25.', 'Answer: 3.75.'] },
  },
  'mult-div-decimals': {
    title: 'Multiplying & Dividing Decimals',
    concept: 'Multiply as if there were no decimal points, then count the total decimal places and place the point in the answer. To divide, bring the point straight up.',
    why: 'Unit prices and splitting bills use decimal multiplication and division.',
    example: { problem: '1.2 × 3', steps: ['12 × 3 = 36.', 'One decimal place in the problem.', 'Answer: 3.6.'] },
  },
  'ratio-intro': {
    title: 'What Is a Ratio?',
    concept: 'A ratio compares two amounts, written a:b or "a to b". Ratios can be simplified just like fractions.',
    why: 'Ratios mix paint, scale recipes, and compare teams.',
    example: { problem: '4 red to 6 blue — simplest ratio?', steps: ['Write 4:6.', 'Both divide by 2.', 'Simplest: 2:3.'] },
  },
  'ratio-tables': {
    title: 'Ratio Tables',
    concept: 'A ratio table lists equivalent ratios in rows/columns. Multiply both quantities by the same number to fill it in.',
    why: 'Ratio tables scale recipes and mixtures up or down.',
    example: { problem: '1 cup sugar : 2 cups flour. Flour for 3 cups sugar?', steps: ['Sugar ×3 (1→3).', 'Flour ×3 too.', '2 × 3 = 6 cups flour.'] },
  },
  'equivalent-ratios': {
    title: 'Equivalent Ratios',
    concept: 'Two ratios are equivalent if you can multiply both parts of one by the same number to get the other. Adding to both does NOT keep them equal.',
    why: 'Spotting equal ratios helps you check if two mixtures taste the same.',
    example: { problem: 'Is 2:3 equal to 6:9?', steps: ['2 × 3 = 6.', '3 × 3 = 9.', 'Both ×3 → yes, equivalent.'] },
  },
  'proportions': {
    title: 'Proportions',
    concept: 'A proportion says two ratios are equal: a/b = c/d. Solve for a missing value by cross-multiplying.',
    why: 'Proportions convert units and figure out "how much for how many".',
    example: { problem: 'Solve 2/3 = 4/x', steps: ['Cross-multiply: 2·x = 3·4.', '2x = 12.', 'x = 6.'] },
  },
  'solve-proportion': {
    title: 'Solving with Proportions',
    concept: 'Set up matching ratios (keep the same units on top and bottom), then cross-multiply and divide to find the unknown.',
    why: 'Maps, models, and scaled drawings all rely on proportions.',
    example: { problem: '1 cm = 5 km. How far is 4 cm?', steps: ['1/5 = 4/x.', 'x = 5 × 4.', 'x = 20 km.'] },
  },
  'percent-of': {
    title: 'Percent of a Number',
    concept: 'Percent means "out of 100". Turn the percent into a decimal (divide by 100), then multiply by the number.',
    why: 'Tips, test scores, and sales are all "percent of" a number.',
    example: { problem: 'What is 25% of 80?', steps: ['25% = 0.25.', '0.25 × 80.', '= 20.'] },
  },
  'percent-convert': {
    title: 'Percent ↔ Decimal ↔ Fraction',
    concept: 'Percent to decimal: divide by 100 (move point left twice). Decimal to percent: multiply by 100. Fractions convert through their decimal.',
    why: 'Different forms make different problems easier.',
    example: { problem: 'Write 40% three ways.', steps: ['Decimal: 0.40.', 'Fraction: 40/100 = 2/5.', 'All equal 40%.'] },
  },
  'percent-change': {
    title: 'Percent Increase & Decrease',
    concept: 'Find the percent of the original amount, then add it (increase) or subtract it (decrease) from the original.',
    why: 'Prices rise and fall, and populations grow — all percent change.',
    example: { problem: '$50 increased by 20%', steps: ['20% of 50 = 10.', 'Increase → add.', '50 + 10 = $60.'] },
  },
  'discount-tax': {
    title: 'Discounts & Tax',
    concept: 'A discount subtracts a percent of the price; tax adds a percent. Find the percent amount first, then add or subtract.',
    why: 'This is real shopping math — sale prices and final totals.',
    example: { problem: '$40 jacket, 25% off', steps: ['25% of 40 = 10.', 'Discount → subtract.', 'Sale price = $30.'] },
  },
  'variables-intro': {
    title: 'What Is a Variable?',
    concept: 'A variable is a letter that stands for an unknown or changing number. 3x means "3 times some number x".',
    why: 'Variables let us write one rule that works for any number.',
    example: { problem: 'Boxes of 6. Total for b boxes?', steps: ['Each box = 6.', 'b boxes → 6 × b.', 'Expression: 6b.'] },
  },
  'write-expressions': {
    title: 'Writing Expressions',
    concept: 'Translate words into math: "more than" = +, "less than" = −, "times" = ×, "quotient" = ÷. Keep the variable as named.',
    why: 'Turning words into math is the first step to solving real problems.',
    example: { problem: '"5 more than n"', steps: ['"more than" means add.', 'Start with n.', 'Answer: n + 5.'] },
  },
  'evaluate-expressions': {
    title: 'Evaluating Expressions',
    concept: 'To evaluate, replace the variable with its value (use parentheses), then follow order of operations.',
    why: 'Plugging in numbers is how formulas turn into real answers.',
    example: { problem: 'Evaluate 3x + 2 when x = 4', steps: ['Substitute: 3(4) + 2.', '12 + 2.', '= 14.'] },
  },
  'equation-intro': {
    title: 'What Is an Equation?',
    concept: 'An equation says two things are equal, using =. A solution is a value that makes both sides truly equal.',
    why: 'Equations are balance scales — the heart of algebra.',
    example: { problem: 'Is x=5 a solution of x+3=8?', steps: ['Substitute 5.', '5 + 3 = 8. ✓', 'Yes, x = 5 works.'] },
    visual: 'left side  =  right side  (balanced)',
  },
  'one-step': {
    title: 'One-Step Equations',
    concept: 'Get the variable alone by doing the OPPOSITE operation to BOTH sides. Addition undoes subtraction; multiplication undoes division.',
    why: 'One-step equations are the building block of all equation solving.',
    example: { problem: 'Solve x + 7 = 12', steps: ['Subtract 7 from both sides.', 'x = 12 − 7.', 'x = 5.'] },
  },
  'two-step': {
    title: 'Two-Step Equations',
    concept: 'First undo addition/subtraction, then undo multiplication/division — always to both sides.',
    why: 'Most real formulas need two or more steps to solve.',
    example: { problem: 'Solve 2x + 3 = 11', steps: ['Subtract 3: 2x = 8.', 'Divide by 2.', 'x = 4.'] },
  },
  'word-to-equation': {
    title: 'Word Problems → Equations',
    concept: 'Name the unknown with a variable, translate the sentence into an equation, then solve it.',
    why: 'This is the superpower — turning a story into math you can solve.',
    example: { problem: '$3/mile + $2 start = $14. Miles?', steps: ['3m + 2 = 14.', '3m = 12.', 'm = 4 miles.'] },
  },
  'inequalities-intro': {
    title: 'Introducing Inequalities',
    concept: 'Inequalities compare with > (greater), < (less), ≥ (at least), ≤ (at most). The open side faces the bigger value.',
    why: '"You must be at least 10" and "spend under $20" are inequalities.',
    example: { problem: 'Fill in: 8 ? 5', steps: ['8 is bigger than 5.', 'Open side faces 8.', '8 > 5.'] },
  },
  'solve-inequalities': {
    title: 'Solving Inequalities',
    concept: 'Solve like an equation — do the same to both sides — but the answer is a range of values, not a single number.',
    why: 'Budgets and limits are ranges, not single answers.',
    example: { problem: 'Solve x + 3 < 7', steps: ['Subtract 3.', 'x < 4.', 'Any number below 4 works.'] },
  },
  'graph-inequalities': {
    title: 'Graphing Inequalities',
    concept: 'On a number line, an open circle means "not included" (> or <); a closed circle means "included" (≥ or ≤). Shade toward the allowed values.',
    why: 'A picture shows every solution at once.',
    example: { problem: 'Graph x ≥ 3', steps: ['3 is included → closed circle.', 'x can be larger.', 'Shade to the right.'] },
    visual: '●━━━▶  (x ≥ 3)',
  },
  'input-output': {
    title: 'Input/Output Tables',
    concept: 'A rule turns each input into an output. Apply the rule to every input to fill the table.',
    why: 'Machines, prices, and functions all map inputs to outputs.',
    example: { problem: 'Rule ×2+1. Input 3?', steps: ['3 × 2 = 6.', '6 + 1 = 7.', 'Output: 7.'] },
  },
  'pattern-rules': {
    title: 'Patterns & Rules',
    concept: 'Find what changes between terms. A constant jump means "add that number each time".',
    why: 'Spotting patterns predicts what comes next — the core of math thinking.',
    example: { problem: 'Next: 2, 5, 8, 11, __', steps: ['Each step +3.', '11 + 3.', 'Next is 14.'] },
  },
  'functions-intro': {
    title: 'Introduction to Functions',
    concept: 'A function gives exactly one output for each input. f(x) = 2x + 1 means "double x, then add 1". f(3) means "put 3 in for x".',
    why: 'Functions are the language of science, coding, and graphs.',
    example: { problem: 'f(x)=2x+1, find f(3)', steps: ['Put 3 in for x.', '2(3) + 1.', 'f(3) = 7.'] },
  },
  'geometry-basics': {
    title: 'Points, Lines & Angles',
    concept: 'A point marks a spot; a line goes forever both ways. Angles: right = 90°, acute < 90°, obtuse between 90° and 180°.',
    why: 'Everything you build or draw uses points, lines, and angles.',
    example: { problem: 'A 45° angle is...?', steps: ['Compare to 90°.', '45 < 90.', 'It is acute.'] },
  },
  'triangles-quads': {
    title: 'Triangles & Quadrilaterals',
    concept: 'Triangles: equilateral (all equal), isosceles (two equal), scalene (none). Quadrilaterals have 4 sides: squares, rectangles, and more.',
    why: 'Recognizing shapes is the start of geometry and design.',
    example: { problem: 'All 3 sides equal — which triangle?', steps: ['All sides equal.', 'That is the definition.', 'Equilateral.'] },
  },
  'perimeter-area': {
    title: 'Perimeter & Area',
    concept: 'Perimeter is the distance around (add all sides). Area is the space inside (for a rectangle, length × width, in square units).',
    why: 'Fencing a yard uses perimeter; carpeting a floor uses area.',
    example: { problem: 'Rectangle 5 by 3: area?', steps: ['Area = length × width.', '5 × 3.', '= 15 square units.'] },
  },
  'circles': {
    title: 'Circles',
    concept: 'Radius = center to edge; diameter = across (2 × radius). Circumference = 2πr (around). Area = πr². Use π ≈ 3.14.',
    why: 'Wheels, pizzas, and clocks are all circles.',
    example: { problem: 'Radius 5: circumference?', steps: ['C = 2πr.', '2 × 3.14 × 5.', '≈ 31.4.'] },
  },
  'surface-volume': {
    title: 'Surface Area & Volume',
    concept: 'Volume is the space inside a solid (a cube: edge³). Surface area is the total outside (a cube: 6 × face area).',
    why: 'Volume fills boxes and tanks; surface area is how much wrapping you need.',
    example: { problem: 'Cube edge 3: volume?', steps: ['Volume = edge³.', '3 × 3 × 3.', '= 27.'] },
  },
  'coordinate-plot': {
    title: 'Plotting Points',
    concept: 'The coordinate plane has an x-axis (across) and y-axis (up/down). A point (x, y) means go x across, then y up/down.',
    why: 'Maps, graphs, and video games all use coordinates.',
    example: { problem: 'Where is (3, 2)?', steps: ['Go 3 right.', 'Then 2 up.', 'Both positive → Quadrant 1.'] },
    visual: '  y\n  ↑\n──┼──▶ x',
  },
  'quadrants': {
    title: 'Quadrants',
    concept: 'The axes split the plane into 4 quadrants, numbered counter-clockwise from the top-right. Signs: Q1 (+,+), Q2 (−,+), Q3 (−,−), Q4 (+,−).',
    why: 'Knowing quadrants tells you directions without plotting.',
    example: { problem: 'Signs in Quadrant 3?', steps: ['Q3 is bottom-left.', 'Left → x negative.', 'Down → y negative: (−,−).'] },
  },
  'graph-equations': {
    title: 'Graphing Equations',
    concept: 'Pick x values, use the equation to find each y, and plot the (x, y) points. A straight-line equation gives a line.',
    why: 'Graphs turn equations into pictures you can read at a glance.',
    example: { problem: 'y = 2x + 1, x = 2?', steps: ['y = 2(2) + 1.', 'y = 5.', 'Point (2, 5) is on the line.'] },
  },
  'unit-conversion': {
    title: 'Unit Conversions',
    concept: 'To change units, multiply by a conversion factor. Going to a smaller unit multiplies (m→cm: ×100); to a bigger unit divides.',
    why: 'Recipes, travel, and science constantly switch units.',
    example: { problem: '3 m to cm', steps: ['1 m = 100 cm.', '3 × 100.', '= 300 cm.'] },
  },
  'time-distance': {
    title: 'Time & Distance',
    concept: 'Distance = speed × time. Rearrange to find any one: speed = distance ÷ time, time = distance ÷ speed.',
    why: 'Travel planning is all speed, time, and distance.',
    example: { problem: '60 km/h for 2 h?', steps: ['Distance = speed × time.', '60 × 2.', '= 120 km.'] },
  },
  'scale-maps': {
    title: 'Scale & Maps',
    concept: 'A scale tells how map distance relates to real distance (1 cm = 5 km). Multiply the map measurement by the scale.',
    why: 'Reading maps and blueprints depends on scale.',
    example: { problem: '1 cm = 10 m. 4 cm = ?', steps: ['Each cm = 10 m.', '4 × 10.', '= 40 m.'] },
  },
  'mean-median-mode': {
    title: 'Mean, Median, Mode & Range',
    concept: 'Mean = average (add, then divide by how many). Median = middle after sorting. Mode = most common. Range = biggest − smallest.',
    why: 'These summarize data — grades, scores, weather.',
    example: { problem: 'Mean of 2, 4, 6?', steps: ['Sum = 12.', 'Divide by 3.', 'Mean = 4.'] },
  },
  'graphs-reading': {
    title: 'Reading Graphs',
    concept: 'Bar graphs compare amounts; line graphs show change over time; pie charts show parts of a whole. Read the labels and scale first.',
    why: 'News, sports, and science are full of graphs to interpret.',
    example: { problem: 'Tallest bar = most. Find the max.', steps: ['Scan the bars.', 'Find the tallest.', 'Read its label.'] },
  },
  'probability-basic': {
    title: 'Basic Probability',
    concept: 'Probability = favorable outcomes ÷ total outcomes. It ranges from 0 (impossible) to 1 (certain).',
    why: 'Games, weather, and predictions all use probability.',
    example: { problem: 'P(red) with 2 red of 5?', steps: ['Favorable = 2.', 'Total = 5.', 'P = 2/5.'] },
  },
  'compound-events': {
    title: 'Compound Events',
    concept: 'For two independent events, count outcomes for each and multiply (the counting principle).',
    why: 'Combinations and chances of "this AND that" use compound events.',
    example: { problem: 'Coin AND die outcomes?', steps: ['Coin: 2.', 'Die: 6.', '2 × 6 = 12.'] },
  },
  'tree-diagrams': {
    title: 'Tree Diagrams',
    concept: 'A tree diagram branches once for each choice, showing every combination. Count the end branches, or multiply the choices.',
    why: 'Trees organize all the possibilities so none are missed.',
    example: { problem: '3 shirts × 2 pants?', steps: ['Each shirt branches to 2 pants.', '3 × 2.', '6 outfits.'] },
  },
}

// Skills used on pure review days have no single topic page.
export const REVIEW_TOPIC = {
  title: 'Review & Challenge',
  concept: 'Today mixes problems from everything you have learned so far. Take your time and use your strategies!',
  why: 'Mixing topics is how you build lasting mastery — just like a real math tournament.',
  example: { problem: 'Warm up your brain!', steps: ['Read carefully.', 'Pick the right strategy.', 'Check your answer.'] },
}
